### ISSUE TITLE
As a curator, I would like a clear visual indicator when viewing an item that been deleted from the filesystem.

### ISSUE THREAD

**Issue by jcreel** [TAMULib/MagpieService#248]
So that I know if it needs deletion from the database or needs to be reconstituted.
Currently, expected images and other resources on the item will fail to load and throw errors.

**Comment by wwelling** [comment]
I personally would like for the MAGPIE database to update its document entry to be able to provide the published resources. Maybe a bit aspirational and kinda like a repository itself, but would be better than failing. This would provide easier access to published resources and enable update/batch update. It would be a shame to close the door on batch updates.

**Comment by wwelling** [comment]
For the case when the resource has been deleted without publishing to IR, this makes sense to inform the user.
